build(MF-21): configured tailwind
KaterynaZhuvak/MyFin pull request #5
Opened 2024-04-17 19:29 UTC by Midomik

Added tailwind plugin to prettir and eslint config files, added basic theme(root) to tailwind config

2024-04-17 19:42 UTC, KaterynaZhuvak reviewed
I think that it can lead to conflict. Because I changed the file aslint as well.

2024-04-17 21:48 UTC, Sk3ll approved these changes

2024-04-17 21:51 UTC, Sk3ll requested changes

2024-04-17 21:51 UTC, Sk3ll commented on src/index.css
Move this file to styles folder

2024-04-18 16:26 UTC, KaterynaZhuvak approved these changes

2024-04-18 16:34 UTC, Sk3ll approved these changes

2024-04-18 16:35 UTC, merged