Mf-9/ESLint
KaterynaZhuvak/MyFin pull request #6
Opened 2024-04-17 19:31 UTC by KaterynaZhuvak

2024-04-17 19:36 UTC, KaterynaZhuvak commented
I just removed the file. If it is incorrect, I will think then what to do next.

2024-04-17 21:45 UTC, Sk3ll requested changes

2024-04-17 21:45 UTC, Sk3ll commented on .prettierrc
This file shouldn't delete or change

2024-04-18 14:48 UTC, Sk3ll commented
Please change PR's name to _build(MF-9): configured eslint_. It shoud look like in Yuriy

2024-04-19 07:54 UTC, Sk3ll requested changes
Please change name of pull request from `Mf-9/ESLint` to `build(MF-9): configured eslint`

2024-04-19 07:54 UTC, Sk3ll commented on .eslintrc.cjs
> +  env: {browser: true, es2020: true},
Please delete this line, should be better if you installed extends `@vercel/style-guide/eslint/browser`. It has more rules.

```suggestion
  extends: [
    require.resolve('@vercel/style-guide/eslint/browser'),
    require.resolve('@vercel/style-guide/eslint/react'),
    require.resolve('@vercel/style-guide/eslint/typescript'),
    'plugin:tailwindcss/recommended',
  ],
```

2024-04-19 07:54 UTC, Sk3ll commented on tsconfig.json
> -  "references": [{ "path": "./tsconfig.node.json" }]
this is bad rule, when we delete this spacing between brackets

2024-04-19 10:57 UTC, Sk3ll requested changes

2024-04-19 10:57 UTC, Sk3ll commented on .eslintrc.cjs
> +const {resolve} = require('node:path');
```suggestion
const { resolve } = require('node:path');
```

2024-04-19 10:57 UTC, Sk3ll commented on README.md
> -
roll back this file

2024-04-19 10:59 UTC, Sk3ll approved these changes

2024-04-19 11:00 UTC, merged